# Place extraEnvFrom under global
global:
  extraEnvFrom:
    - secretRef:
        name: mimir-s3-credentials
mimir:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
  structuredConfig:
    memberlist:
      cluster_label: "mimir"
      cluster_label_verification_disabled: false
    server:
      log_level: info
      # Enable Prometheus compatibility endpoint
      path_prefix: /prometheus
      prometheus_http_prefix_enabled: true

      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      grpc_server_max_concurrent_streams: 1000
    limits:
      max_label_names_per_series: 120
      max_global_series_per_user: 12000000
      ingestion_burst_size: 200000
      ingestion_rate: 150000
      max_global_series_per_metric: 200000000
      compactor_blocks_retention_period: 24h
    blocks_storage:
      backend: s3
      s3:
        endpoint: "s3.ap-south-1.amazonaws.com"
        region: "ap-south-1"
        access_key_id: "${access_key_id}"
        secret_access_key: "${secret_access_key}"
        bucket_name: "eks-sherlock-mimir-blocks"
        insecure: false
    compactor:
      compaction_interval: 24h
# Writes incoming series to long-term storage on the write path and returns series samples for queries on the read path.
ingester:
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    enabled: false
  replicas: 2
# Receives data from alloy, corrects, devides data to batches and send to ingesters
distributor:
  extraArgs:
    auth.multitenancy-enabled: false
    log.level: info
  replicas: 1
# Increases query performance and reduces long-term storage usage by combining blocks.
compactor:
  replicas: 1
# Evaluates PromQL expressions by fetching time series and labels on the read path. Uses store-gateway fron minio and ingester for latest data
querier:
  replicas: 2
# "frontend" for querier
query_frontend:
  replicas: 1
# comuniacation with minio
store_gateway:
  zoneAwareReplication:
    enabled: false
  replicas: 1
## Disabled services:
rollout_operator:
  enabled: false
gateway:
  enabledNonEnterprise: false
ruler:
  enabled: false
query_scheduler:
  enabled: false
overrides_exporter:
  enabled: false
alertmanager:
  enabled: false
minio:
  enabled: false
